version: '3.8'

services:
  otc-bot:
    build: .
    container_name: otc-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db
      - ./banner.jpg:/app/banner.jpg
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
